@ToDoManagement.Api_HostAddress = http://localhost:5241/api/categories

GET {{ToDoManagement.Api_HostAddress}}/019DB728-AA00-7C77-824C-32DEEC58DD7d
Accept: application/json

###

GET {{ToDoManagement.Api_HostAddress}}
Accept: application/json

###
POST {{ToDoManagement.Api_HostAddress}}
Content-Type: application/json

{
  "Name" : "Trabajo"
}